baseURL = "https://zizouhuweidi.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
pagination.pagerSize = 10
summaryLength = 0


weight = 1
title = "~"

[services]
[services.disqus]
shortname = 'https-zizouhuweidi-github-io'

[params.author]
name = "El Zubeir Huweidi"
image = "img/zizouhuweidi.jpg"
headline = "hello, world!"
links = [
  { github = "https://github.com/zizouhuweidi/" },
  { x-twitter = "https://twitter.com/zizouhuweidi/" },
  { linkedin = "https://www.linkedin.com/in/el-zubeir-huweidi-900899234/" },
]

[outputs]
home = ["HTML", "RSS", "JSON"]
