languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "home"
description = "personal website and blog"

dateFormat = "2 January 2006"

[author]
name = "El Zubeir Huweidi"
image = "img/zizouhuweidi.jpg"
headline = "my humble abode on the interwebs; a distributed log of my thoughts and documentation of my journey"
links = [
  { twitter = "https://twitter.com/zizouhuweidi" },
  { github = "https://github.com/zizohuweidi" },
  { linkedin = "https://linkedin.com/in/zizouhuweidi" },
  # { email = "mailto:hi@zubeir.huweidi@gmail.com" },
  # { gitlab = "https://gitlab.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
]
